apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: argocd-studies-goapp
  newName: pedrofurtado/argocd-studies-app
  newTag: a1f3e27d4cf433e82d397e4252142fc11c4aee37
