apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: argocd-studies-goapp
  newName: pedrofurtado/argocd-studies-app
  newTag: 9b7fbb716e5ebc12fc52629c50782bdd06d09940
